### ISSUE TITLE
Application redirection in not heppening .

### ISSUE THREAD

**Issue by arjunnna** [trongdth/OAuth2-for-iOS#1]
Hi ,

After login to fitbit account it is not redirecting to application . giving  below error  can you please address this ?

NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9843)

**Comment by trongdth** [comment]
Hi @arjunnna 

Can you take a screenshot of configured app?

**Comment by trongdth** [comment]
Please test with new version. There is an example for you for testing.
