### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by shashank109** [trongdth/OAuth2-for-iOS#2]
hi.. I am using this library but I am unable to use refresh token.
Can anyone help me out  how refresh token been used after token expired?
Thanks

**Comment by trongdth** [comment]
Hi there,
refresh_token is used for refreshing access_token when it's expired. 
It depends on what service you are using but normally you must call `token` api with params: grant_type=refresh_token and refresh_token=<REFRESH_TOKEN>

Hope this help

**Comment by trongdth** [comment]
Closed.
